### ISSUE TITLE
Transition to Rust

### ISSUE THREAD

**Issue by JoshuaVandaele** [hllhnd/tiepo#1]
The objective of this issue is to rewrite the existing C codebase of Tiepo into the Rust programming language. The rewrite aims to leverage the benefits of Rust such as memory safety, concurrency, and performance while maintaining the functionality and usability of the original tool.

Tasks:

- [ ]  Study the existing C codebase of "Tiepo" to understand its functionality, structure, and redesign the architecture for porting Tiepo to Rust, considering idiomatic Rust patterns.
- [ ]  Test the Rust implementation thoroughly to ensure correctness and reliability, comparing results with the original C version.
- [ ]  Update documentation, including usage instructions and license information, to reflect the transition to Rust.
- [ ]  Prepare for the release of the Rust version of Tiepo, ensuring all necessary artifacts are available and properly documented.
- [ ]  Release the Rust version, encouraging users to migrate and provide feedback on the new implementation.

**Comment by hllhnd** [comment]
I simply do not make safety errors
